name: Update Clash Config
on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC时间3点运行
  workflow_dispatch:  # 允许手动触发
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Update Config
      run: |
        # 这里可以添加自动更新节点的脚本
        echo "配置自动更新于 $(date)" >> ipfoxy_sg.yaml
        
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Auto-update config'
